
language: python

python:
    - 2.7

before_install:
    - pip install -r test-requirements.txt

install:
  - "pip install ."
  - "pip install -r requirements.txt"

# command to run tests
script: nosetests
