globals:
  logs_dir: "{ontimer_root}/logs/j{event_major}/n{event_minor}_t{task_id}_r{run}/"
events:
  - name: price
    vars: 
      - name: region
        type: STR #elements: [ us, eu, asia ]
      - name: time
        type: DATETIME
    generators:
      - name: us
        on_time: 
          timezone: US/Pacific
          onexp: 0 14 * * MON-FRI
        vals: 
          - us
          - eval: dt 
        wait_final_stage: true
    tasks:
      - name: download_prices
        cmd: runipy {ipy_path}/HistoricalPrices.ipynb --html HistoricalPrices.html 
      - name: calculate_returns
        depends_on: [download_prices]
        cmd: runipy {ipy_path}/HistoricalReturns.ipynb --html HistoricalReturns.html 
  - name: tree
    vars: 
      - name: time
        type: DATETIME
    generators:
      - name: 10am
        on_time: 
          timezone: US/Pacific
          onexp: 0 10 * * MON-FRI
        vals: 
          - eval: dt 
        wait_final_stage: true
    tasks:
      - name: start
        cmd: boss --bs 2 
      - name: branch1
        depends_on: [start]
        cmd: boss --bs 3 
      - name: branch2
        depends_on: [start]
        cmd: boss --bs 1
      - name: join1
        depends_on: [branch1, branch2] 
        cmd: boss 
      - name: join2
        depends_on: [join1, branch3] 
        cmd: boss --bs 2
      - name: branch3
        depends_on: [branch2] 
        cmd: boss --bs 3
             